---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: import EPEL Repo GPG Key
  become: true
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
    validate_certs: true

- name: Install EPEL repo
  become: true
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 3
